services:
  node-service:
    build:
      context: ../services/update_data_service/node
      dockerfile: Dockerfile
    networks:
      - container-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  python-service:
    build:
      context: ../services/update_data_service/python
      dockerfile: Dockerfile
    networks:
      - container-network
    depends_on:
      node-service:
        condition: service_healthy

networks:
  container-network:
    driver: bridge
